{"name": "Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [0, 0], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628277071345, "stop": 1628277071346}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628277071346, "stop": 1628277071347}, {"name": "When Set request Body { \"roomSize\" : [3, 3], \"coords\" : [0,0], \"patches\" : [[1,1]], \"instructions\" : \"NESW\" }", "status": "passed", "start": 1628277071347, "stop": 1628277071347}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628277071348, "stop": 1628277071360}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628277071361, "stop": 1628277071362}, {"name": "And Response BODY with the right data [0, 0] and 1", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [0, 0], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628277071362, "stop": 1628277071363}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [3, 3], \"coords\" : [0,0], \"patches\" : [[1,1]], \"instructions\" : \"NESW\" }"}, {"name": "coords", "value": "[0, 0]"}, {"name": "patches", "value": "1"}], "start": 1628277071344, "stop": 1628277071364, "uuid": "bc186ac5-dd27-4952-9923-1f2e2e9dc899", "historyId": "0fe58d661b373956a98e9903e955e1dc", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}