{"name": "One of the coordinate value is '0' for param - coords in the Request Body -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 0], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628433426966, "stop": 1628433426967}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628433426967, "stop": 1628433426968}, {"name": "When Set request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 0], \"patches\" : [ [1, 0], [2, 2], [2, 3] ], \"instructions\" : \"NEWS\" }", "status": "passed", "start": 1628433426968, "stop": 1628433426969}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628433426969, "stop": 1628433426983}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628433426983, "stop": 1628433426984}, {"name": "And Response BODY with the right data [1, 0] and 1", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 0], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628433426984, "stop": 1628433426985}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 0], \"patches\" : [ [1, 0], [2, 2], [2, 3] ], \"instructions\" : \"NEWS\" }"}, {"name": "coords", "value": "[1, 0]"}, {"name": "patches", "value": "1"}], "start": 1628433426964, "stop": 1628433426986, "uuid": "7ab9b239-0fc3-47c4-a74f-777e41c96877", "historyId": "777f930e74c56d60b435655b103f10f8", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for coords params: One of the coordinate value is '0' for param - coords in the Request Body", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for coords params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}