{"name": "Invalid value for param - Patches in the Request Body and getting Incorrect output -- @1.6 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 3], 'patches': 1}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628184586106, "stop": 1628184586107}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628184586108, "stop": 1628184586109}, {"name": "When Set invalid request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [2, 2] ], \"patches\" : [ [1, 2] ], \"instructions\" : \"NNESEESWNWW\" }", "status": "passed", "start": 1628184586109, "stop": 1628184586110}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628184586111, "stop": 1628184586137}, {"name": "Then I receive error 500, \"Internal Server Error\"", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 3], 'patches': 1}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628184586138, "stop": 1628184586139}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [2, 2] ], \"patches\" : [ [1, 2] ], \"instructions\" : \"NNESEESWNWW\" }"}, {"name": "response_code", "value": "500"}, {"name": "response_error", "value": "Internal Server Error"}], "start": 1628184586104, "stop": 1628184586141, "uuid": "b7deb46e-f4c3-44a8-a527-c74aaeb58867", "historyId": "7d037717985670ac6f340686461a970e", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Invalid value for param - Patches in the Request Body and getting Incorrect output", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}