{"name": "One of the coordinate value is '0' for param - patches in the Request Body -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628184045402, "stop": 1628184045402}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628184045403, "stop": 1628184045403}, {"name": "When Set request Body { \"roomSize\" : [5,5], \"coords\" : [1, 2], \"patches\" : [[0, 2]], \"instructions\" : \"NEWSNEWS\" }", "status": "passed", "start": 1628184045403, "stop": 1628184045404}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628184045405, "stop": 1628184045415}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628184045415, "stop": 1628184045416}, {"name": "And Response BODY with the right data [1, 2] and 0", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628184045417, "stop": 1628184045418}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5,5], \"coords\" : [1, 2], \"patches\" : [[0, 2]], \"instructions\" : \"NEWSNEWS\" }"}, {"name": "coords", "value": "[1, 2]"}, {"name": "patches", "value": "0"}], "start": 1628184045401, "stop": 1628184045419, "uuid": "42d24030-4813-4c4d-9e92-f1a2ec6d115f", "historyId": "e9517b1793fac0ac3d8904a13968b64a", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: One of the coordinate value is '0' for param - patches in the Request Body", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}