{"name": "Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [0, 0], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628184585562, "stop": 1628184585563}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628184585563, "stop": 1628184585564}, {"name": "When Set request Body { \"roomSize\" : [3, 3], \"coords\" : [0,0], \"patches\" : [[1,1]], \"instructions\" : \"NESW\" }", "status": "passed", "start": 1628184585564, "stop": 1628184585565}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628184585566, "stop": 1628184585606}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628184585607, "stop": 1628184585608}, {"name": "And Response BODY with the right data [0, 0] and 1", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [0, 0], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628184585608, "stop": 1628184585609}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [3, 3], \"coords\" : [0,0], \"patches\" : [[1,1]], \"instructions\" : \"NESW\" }"}, {"name": "coords", "value": "[0, 0]"}, {"name": "patches", "value": "1"}], "start": 1628184585560, "stop": 1628184585610, "uuid": "a0dd6b73-79e0-411c-9098-e9be691368af", "historyId": "0fe58d661b373956a98e9903e955e1dc", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}