{"name": "One of the coordinate value is '0' for param - patches in the Request Body -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628093068134, "stop": 1628093068135}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628093068135, "stop": 1628093068136}, {"name": "When Set request Body { \"roomSize\" : [5,5], \"coords\" : [1, 2], \"patches\" : [[1, 0]], \"instructions\" : \"NEWSNEWS\" }", "status": "passed", "start": 1628093068136, "stop": 1628093068137}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628093068137, "stop": 1628093068148}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628093068148, "stop": 1628093068149}, {"name": "And Response BODY with the right data [1, 2] and 0", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628093068149, "stop": 1628093068150}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5,5], \"coords\" : [1, 2], \"patches\" : [[1, 0]], \"instructions\" : \"NEWSNEWS\" }"}, {"name": "coords", "value": "[1, 2]"}, {"name": "patches", "value": "0"}], "start": 1628093068132, "stop": 1628093068152, "uuid": "07cd31f2-7511-47e3-8a92-0eaf455e727b", "historyId": "028cd67d9a9b5535eb9967afe78f2431", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: One of the coordinate value is '0' for param - patches in the Request Body", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}