{"name": "Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches -- @1.4 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 3], 'patches': 1}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628093067871, "stop": 1628093067872}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628093067872, "stop": 1628093067873}, {"name": "When Set request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ ], \"instructions\" : \"NNESEESWNWW\" }", "status": "passed", "start": 1628093067874, "stop": 1628093067874}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628093067875, "stop": 1628093067887}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628093067887, "stop": 1628093067888}, {"name": "And Response BODY with the right data [1, 3] and 0", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 3], 'patches': 1}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628093067888, "stop": 1628093067889}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ ], \"instructions\" : \"NNESEESWNWW\" }"}, {"name": "coords", "value": "[1, 3]"}, {"name": "patches", "value": "0"}], "start": 1628093067869, "stop": 1628093067891, "uuid": "a354441c-5020-49f2-9ae3-b99e01248a21", "historyId": "f76e5a5260c0a38990114e185049b009", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}