{"name": "Invalid value for param - coords in the Request Body and getting Incorrect output -- @1.6 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628093067536, "stop": 1628093067537}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628093067537, "stop": 1628093067538}, {"name": "When Set invalid request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"coords\" : [2, 1], \"patches\" : [ [2, 2] ], \"instructions\" : \"NNESEESWNWW\" }", "status": "passed", "start": 1628093067538, "stop": 1628093067538}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628093067539, "stop": 1628093067550}, {"name": "Then I receive error 500, \"Internal Server Error\"", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 2], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 78, in verify_response_code_error\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628093067551, "stop": 1628093067552}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"coords\" : [2, 1], \"patches\" : [ [2, 2] ], \"instructions\" : \"NNESEESWNWW\" }"}, {"name": "response_code", "value": "500"}, {"name": "response_error", "value": "Internal Server Error"}], "start": 1628093067534, "stop": 1628093067553, "uuid": "b4c44ed4-53a0-4d93-b19f-7ea7230bf706", "historyId": "d4aa5f99ad7e1b17019d746d9ac3b46c", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for coords params: Invalid value for param - coords in the Request Body and getting Incorrect output", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for coords params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}